---
title: "4.2 Exercise"
author: "Harlan Wittlieff"
date: "5/4/2022"
output: pdf_document
---

```{r setup, include=FALSE}
# Load Library

df <- read.csv("Data/crimerates-by-state-2005.csv")
```

```{r}
# Load Libraries
library(ggplot2)
library(dplyr)
```

```{r}
# Remove USA & District of Columbia rows
df <- df[-c(1, 10),]
```


```{r}
ggplot(df, aes(x=robbery, y=murder))+ geom_point(colour='darkblue') + theme_bw() + theme(panel.border = element_blank(), 
      panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "grey")) + xlab("Robberies per 100,000 Population") + ylab("Murders per 100,000 Population") + ggtitle("Robberies vs. Murders in the U.S.") + geom_text(label=df$state, size=3, hjust=-.1)
```

```{r}
ggplot(df, aes(x=robbery, y=murder, size=population))+ geom_point(colour='darkblue') + theme_bw() + theme(panel.border = element_blank(), 
      panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "grey")) + xlab("Robberies per 100,000 Population") + ylab("Murders per 100,000 Population") + ggtitle("Robberies vs. Murders in the U.S.") + geom_text(label=df$state, size=3, hjust=-.1)
```

```{r}
ggplot(df, aes(x=murder)) + geom_density()+ theme_bw() + theme(panel.border = element_blank(), 
      panel.grid.major = element_blank(), panel.grid.minor = element_blank(), axis.line = element_line(colour = "grey")) + xlab("Murders per 100,000 Population") + ylab("Density") + ggtitle("U.S. Murder Rate by State")
```

